/**
 * Theme factory + 48 extended themes inspired by md2wechat.app theme gallery.
 *
 * Each theme is described by a compact color config; the full `styles` object
 * (16 element selectors matching the original theme files) is generated by
 * `makeStyles()` below. Adding a new theme is ~12 lines instead of ~30+.
 */

import type { Theme } from './types';

export interface Palette {
  id: string;
  name: string;
  description: string;
  font: string;
  bg: string;          // page background
  text: string;        // body color
  heading: string;     // h1/h2 color
  subheading: string;  // h3/h4 color
  primary: string;     // brand color (links, accents)
  surface: string;     // blockquote/code background
  surfaceText: string; // blockquote/code text
  border: string;      // hr/table borders
  divider: string;     // hairline dividers
  codeBg: string;
  codeText: string;
  emphasisBg?: string; // optional highlighted bg behind <strong>
  emphasisText?: string;
  surfaceBorder?: string; // blockquote left border / surface border
  isDark?: boolean;
}

const SURFACE_BORDER = (p: Palette) => p.surfaceBorder ?? p.primary;

export function makeStyles(p: Palette): Record<string, string> {
  const surfaceBorder = SURFACE_BORDER(p);
  const emphasisBg = p.emphasisBg ?? 'transparent';
  const emphasisText = p.emphasisText ?? p.heading;
  const hrBg = p.border;
  const thBg = p.isDark ? p.surface : lighten(p.bg);
  const tableBorder = p.border;

  return {
    container: `max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: ${p.font}; font-size: 16px; line-height: 1.7 !important; color: ${p.text} !important; background-color: ${p.bg} !important; word-wrap: break-word;`,
    h1: `font-size: 32px; font-weight: 700; color: ${p.heading} !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em; `,
    h2: `font-size: 26px; font-weight: 600; color: ${p.heading} !important; line-height: 1.35 !important; margin: 32px 0 16px;`,
    h3: `font-size: 21px; font-weight: 600; color: ${p.subheading} !important; line-height: 1.4 !important; margin: 28px 0 14px;`,
    h4: `font-size: 18px; font-weight: 600; color: ${p.subheading} !important; line-height: 1.4 !important; margin: 24px 0 12px;`,
    p: `margin: 18px 0 !important; line-height: 1.7 !important; color: ${p.text} !important;`,
    strong: `font-weight: 700; color: ${emphasisText} !important; background-color: ${emphasisBg}; padding: 0 4px; border-radius: 4px;`,
    em: `font-style: italic; color: ${p.subheading} !important;`,
    a: `color: ${p.primary} !important; text-decoration: none; border-bottom: 1px solid ${p.primary}; padding-bottom: 1px;`,
    ul: `margin: 16px 0; padding-left: 28px;`,
    ol: `margin: 16px 0; padding-left: 28px;`,
    li: `margin: 8px 0; line-height: 1.7 !important; color: ${p.text} !important;`,
    blockquote: `margin: 24px 0; padding: 16px 20px; background-color: ${p.surface} !important; border-left: 4px solid ${surfaceBorder}; color: ${p.surfaceText} !important; border-radius: 4px; `,
    code: `font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: ${p.codeBg} !important; color: ${p.codeText} !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;`,
    pre: `margin: 24px 0; padding: 20px; background-color: ${p.codeBg} !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;`,
    hr: `margin: 36px auto; border: none; height: 1px; background-color: ${hrBg} !important; width: 100%;`,
    img: `max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;`,
    table: `width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;`,
    th: `background-color: ${thBg} !important; padding: 12px 16px; text-align: left; font-weight: 600; color: ${p.subheading} !important; border: 1px solid ${tableBorder};`,
    td: `padding: 12px 16px; border: 1px solid ${tableBorder}; color: ${p.text} !important;`,
    tr: `border: none;`,
  };
}

function lighten(hex: string): string {
  // quick light tint: 6 hex chars
  const m = hex.replace('#', '');
  const r = parseInt(m.slice(0, 2), 16);
  const g = parseInt(m.slice(2, 4), 16);
  const b = parseInt(m.slice(4, 6), 16);
  const mix = (c: number) => Math.round(c + (255 - c) * 0.9).toString(16).padStart(2, '0');
  return '#' + mix(r) + mix(g) + mix(b);
}

function darken(hex: string, amount = 0.85): string {
  const m = hex.replace('#', '');
  const r = parseInt(m.slice(0, 2), 16);
  const g = parseInt(m.slice(2, 4), 16);
  const b = parseInt(m.slice(4, 6), 16);
  const mix = (c: number) => Math.round(c * amount).toString(16).padStart(2, '0');
  return '#' + mix(r) + mix(g) + mix(b);
}

const SYS = '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif';
const SERIF = 'Georgia, "Times New Roman", Times, serif';
const MONO = '"SF Mono", "Fira Code", Consolas, monospace';

function palette(p: Partial<Palette> & Pick<Palette, 'id' | 'name' | 'description' | 'bg' | 'text' | 'heading' | 'primary'>): Palette {
  const isDark = (p as any).isDark ?? false;
  return {
    font: p.font ?? SYS,
    subheading: p.subheading ?? p.heading,
    surface: p.surface ?? lighten(p.bg),
    surfaceText: p.surfaceText ?? p.text,
    border: p.border ?? (isDark ? '#333333' : '#eaeaea'),
    divider: p.divider ?? (isDark ? '#222222' : '#f0f0f0'),
    codeBg: p.codeBg ?? (isDark ? '#1a1a1a' : lighten(p.bg)),
    codeText: p.codeText ?? p.primary,
    ...p,
  } as Palette;
}

const PALETTES: Palette[] = [
  // 1. 极简白（默认）
  palette({ id: 'pure-white', name: '极简白', description: '纯净留白的万能基础款，日常记录首选', bg: '#ffffff', text: '#1d1d1f', heading: '#111111', primary: '#0066cc' }),
  // 2. 墨黑
  palette({ id: 'ink-black', name: '墨黑', description: '极致克制的黑白灰，文艺青年气质', bg: '#fafafa', text: '#2a2a2a', heading: '#0a0a0a', primary: '#1a1a1a', border: '#dcdcdc' }),
  // 3. 暖米黄
  palette({ id: 'warm-cream', name: '暖米黄', description: '羊皮纸般的温润质感，长文阅读舒适', bg: '#fdfaf3', text: '#3d342a', heading: '#2c1f14', primary: '#8c5a3a' }),
  // 4. 燕麦卡其
  palette({ id: 'oat-khaki', name: '燕麦卡其', description: '温润大地色，文学哲思类深度长文', bg: '#f8f6f0', text: '#2b2b2b', heading: '#b75c3d', primary: '#b75c3d', surface: '#f0ece4' }),
  // 5. 沙岩灰
  palette({ id: 'sandstone', name: '沙岩灰', description: '沙漠岩石质感，旅行游记的视觉伙伴', bg: '#ede5d6', text: '#3a342b', heading: '#5a3a1c', primary: '#a8693a' }),
  // 6. 蓝墨水
  palette({ id: 'blue-ink', name: '蓝墨水', description: '复古钢笔蓝，经典书写感', bg: '#f5f7fa', text: '#1c2a3a', heading: '#0e1a2a', primary: '#1e4d8b' }),
  // 7. 海军蓝
  palette({ id: 'navy', name: '海军蓝', description: '深邃专业感，金融商业内容首选', bg: '#f0f3f8', text: '#1a2433', heading: '#0d1726', primary: '#003366', border: '#d6dde6' }),
  // 8. 商务灰蓝
  palette({ id: 'slate', name: '商务灰蓝', description: '职场效率配色，飞书 Notion 气质', bg: '#f7f8fa', text: '#1f2329', heading: '#111827', primary: '#3370ff' }),
  // 9. 极光紫
  palette({ id: 'aurora', name: '极光紫', description: '渐变紫罗兰，极光般的浪漫科技感', bg: '#fbfaff', text: '#2a2440', heading: '#5e35b1', primary: '#7c4dff', surface: '#f0eaff' }),
  // 10. 葡萄紫
  palette({ id: 'grape', name: '葡萄紫', description: '高贵典雅的葡萄酒色，艺术鉴赏专属', bg: '#fdf7fa', text: '#3d2c4a', heading: '#6a1b9a', primary: '#8e24aa' }),
  // 11. 樱花粉
  palette({ id: 'sakura-pink', name: '樱花粉', description: '温柔少女心，生活方式与情感表达', bg: '#fef7f9', text: '#4a3f4f', heading: '#c44569', primary: '#c44569', surface: '#fceef2' }),
  // 12. 玫瑰金
  palette({ id: 'rose-gold', name: '玫瑰金', description: '轻奢时尚配色，美妆穿搭内容', bg: '#fdf6f3', text: '#4a3a35', heading: '#a85644', primary: '#b76e57' }),
  // 13. 蜜桃橘
  palette({ id: 'peach', name: '蜜桃橘', description: '夏日蜜桃的温柔暖意', bg: '#fff7f0', text: '#4a3025', heading: '#e76a3a', primary: '#e76a3a', surface: '#ffe9d6' }),
  // 14. 落日金
  palette({ id: 'sunset-gold', name: '落日金', description: '黄昏金色的散文意境', bg: '#fdf6ee', text: '#3d2c1e', heading: '#c0582a', primary: '#c0582a', surface: '#f8ead6' }),
  // 15. 森林绿
  palette({ id: 'forest', name: '森林绿', description: '沉稳自然系，户外与生活方式', bg: '#f0faf5', text: '#2d4a3e', heading: '#1a7a5a', primary: '#1a7a5a', surface: '#e0f5ec' }),
  // 16. 抹茶绿
  palette({ id: 'matcha', name: '抹茶绿', description: '日式抹茶的淡雅清新', bg: '#f4f9ed', text: '#3a4a2a', heading: '#6a8f3a', primary: '#7aaf3a', surface: '#e8f3d4' }),
  // 17. 微信原生绿
  palette({ id: 'wechat-green', name: '微信原生', description: '原汁原味的官方绿底纹，传统阅读习惯', bg: '#ffffff', text: '#333333', heading: '#111111', primary: '#07c160', surface: '#f0f7f2', border: '#d8e8dc' }),
  // 18. 鼠尾草
  palette({ id: 'sage', name: '鼠尾草', description: '低饱和草本绿，舒缓阅读', bg: '#f5f7f2', text: '#3a4535', heading: '#5a7050', primary: '#7a9070' }),
  // 19. 薄荷青
  palette({ id: 'mint', name: '薄荷青', description: '清凉薄荷绿，生活方式与健康类', bg: '#f0faf5', text: '#2d4a3e', heading: '#1a7a5a', primary: '#1a7a5a' }),
  // 20. 青瓷
  palette({ id: 'celadon', name: '青瓷', description: '宋瓷釉色般的东方雅致', bg: '#f2f7f5', text: '#2c3a36', heading: '#3a5a4f', primary: '#5a8a7a' }),
  // 21. 茶绿
  palette({ id: 'tea-green', name: '茶绿', description: '清茶般的中式素雅', bg: '#f5f9f2', text: '#2f3a28', heading: '#556b2f', primary: '#6b8e23' }),
  // 22. 柠檬黄
  palette({ id: 'lemon', name: '柠檬黄', description: '活力满满柠檬黄，心情向阳', bg: '#fffef5', text: '#4a4520', heading: '#b8860b', primary: '#daa520', surface: '#fff8d6' }),
  // 23. 向日葵
  palette({ id: 'sunflower', name: '向日葵', description: '明亮阳光黄，乐观情绪的传递者', bg: '#fffcf0', text: '#5a4a20', heading: '#e6a817', primary: '#f0a500' }),
  // 24. 沙漠驼
  palette({ id: 'desert-camel', name: '沙漠驼', description: '驼色温暖质感，复古穿搭', bg: '#faf4ec', text: '#4a3a25', heading: '#8b6f3f', primary: '#a8845a' }),
  // 25. 焦糖拿铁
  palette({ id: 'caramel-latte', name: '焦糖拿铁', description: '咖啡馆般的慵懒温暖', bg: '#faf3eb', text: '#3d2c1e', heading: '#7a4f2c', primary: '#9c6a44' }),
  // 26. 深棕
  palette({ id: 'dark-brown', name: '深棕', description: '沉静木质色，古典文学气质', bg: '#f7f1e8', text: '#3a2c1e', heading: '#5a3a1a', primary: '#7a4a2a' }),
  // 27. 火漆红
  palette({ id: 'wax-seal-red', name: '火漆红', description: '复古火漆印章，人文历史与艺术鉴赏', bg: '#f4ecd8', text: '#2b2621', heading: '#8c2211', primary: '#8c2211', surface: '#efe5cc' }),
  // 28. 番茄红
  palette({ id: 'tomato', name: '番茄红', description: '热烈番茄的食欲诱惑', bg: '#fff5f3', text: '#4a2018', heading: '#d32f2f', primary: '#e53935' }),
  // 29. 朱砂红
  palette({ id: 'cinnabar', name: '朱砂红', description: '中式朱砂的东方大气', bg: '#fdf3f3', text: '#4a201a', heading: '#a8281c', primary: '#c0392b' }),
  // 30. 酒红
  palette({ id: 'wine-red', name: '酒红', description: '醇厚葡萄酒色，品味感', bg: '#fbf3f4', text: '#3d1e22', heading: '#722f37', primary: '#8b2635' }),
  // 31. 粉灰
  palette({ id: 'pink-gray', name: '粉灰', description: '克制甜美的莫兰迪粉', bg: '#f5f0f0', text: '#4a3a3a', heading: '#a87880', primary: '#c49898' }),
  // 32. 雾霾蓝
  palette({ id: 'haze-blue', name: '雾霾蓝', description: '莫兰迪蓝灰，宁静致远', bg: '#f0f4f7', text: '#3a4a55', heading: '#5a7a8a', primary: '#7a98a8' }),
  // 33. 长春花蓝
  palette({ id: 'periwinkle', name: '长春花蓝', description: '舒缓心理的年度代表色', bg: '#f5f5fb', text: '#3d3a55', heading: '#5a5a9c', primary: '#7a7ac8' }),
  // 34. 午夜深蓝
  palette({ id: 'midnight-blue', name: '午夜深蓝', description: '沉浸式的海洋系叙事感', bg: '#0c2233', text: '#c8d6e5', heading: '#ff6b6b', subheading: '#54a0ff', primary: '#feca57', surface: '#152d42', border: '#1e3a52', divider: '#1e3a52', codeBg: '#152d42', codeText: '#ff6b6b', isDark: true, font: SYS }),
  // 35. 深海蓝
  palette({ id: 'deep-sea', name: '深海', description: '比午夜更深的远洋蓝', bg: '#0a1a2a', text: '#aac8d8', heading: '#4ecdc4', primary: '#4ecdc4', surface: '#15243a', border: '#1e3a52', isDark: true }),
  // 36. 暗夜赛博
  palette({ id: 'cyberpunk', name: '赛博朋克', description: '粉青撞色的视觉冲击', bg: '#282a36', text: '#f8f8f2', heading: '#bd93f9', subheading: '#8be9fd', primary: '#ff79c6', surface: '#44475a', surfaceText: '#f8f8f2', border: '#6272a4', codeBg: '#44475a', codeText: '#50fa7b', isDark: true }),
  // 37. 暗夜极光
  palette({ id: 'nord', name: '北欧极光', description: '冷静克制的极光蓝', bg: '#2e3440', text: '#d8dee9', heading: '#88c0d0', subheading: '#81a1c1', primary: '#88c0d0', surface: '#3b4252', border: '#4c566a', codeBg: '#3b4252', codeText: '#a3be8c', isDark: true }),
  // 38. 暗夜 GitHub
  palette({ id: 'linear', name: 'Linear 暗夜', description: '纯正暗夜赛博极客风', bg: '#101114', text: '#f1f1f2', heading: '#ffffff', primary: '#5e6ad2', surface: '#1a1a1a', surfaceText: '#cccccc', border: '#333333', codeBg: '#1a1a2e', codeText: '#5e6ad2', isDark: true }),
  // 39. 终端黑
  palette({ id: 'bloomberg', name: '金融终端', description: '华尔街古老终端机，硬派科技代码', bg: '#000000', text: '#15fa52', heading: '#ffffff', subheading: '#eeeeee', primary: '#15fa52', surface: '#0a0a0a', surfaceText: '#cccccc', border: '#333333', codeBg: '#0a0a0a', codeText: '#ff8c00', isDark: true, font: MONO }),
  // 40. 暗夜 Monokai
  palette({ id: 'monokai', name: 'Monokai', description: '经典代码编辑器配色', bg: '#272822', text: '#f8f8f2', heading: '#f92672', subheading: '#e6db74', primary: '#a6e22e', surface: '#3e3d32', surfaceText: '#a6a68a', border: '#49483e', codeBg: '#3e3d32', codeText: '#a6e22e', isDark: true, font: MONO }),
  // 41. 复古做旧
  palette({ id: 'retro', name: 'Retro 复古', description: '做旧羊皮纸搭配火漆红', bg: '#f4ecd8', text: '#2b2621', heading: '#2b2621', subheading: '#2b2621', primary: '#8c2211', surface: '#efe5cc', border: '#d4c9ae', font: SERIF }),
  // 42. 老派新闻
  palette({ id: 'nyt', name: 'NYT 新闻', description: '经典米黄色新闻纸，严肃深度报道', bg: '#fdfaf6', text: '#000000', heading: '#111111', primary: '#326891', surface: '#f0ede8', border: '#d5cfc5', font: SERIF }),
  // 43. 哈利波特
  palette({ id: 'hogwarts', name: '霍格沃茨', description: '古堡羊皮纸，魔法奇幻文学', bg: '#ede4cd', text: '#2a221a', heading: '#5c3317', primary: '#7c4a1e', surface: '#dccfae', border: '#bba882', font: SERIF }),
  // 44. 中式信笺
  palette({ id: 'letter-paper', name: '中式信笺', description: '传统宣纸纹理，东方文学美', bg: '#f7f1e1', text: '#2a1f12', heading: '#5a1a1a', primary: '#8c3030', surface: '#ede5cb', border: '#d4c5a0', font: SERIF }),
  // 45. 极简 Medium
  palette({ id: 'medium', name: 'Medium', description: '简约柔和的西式博客排版', bg: '#fcfcfc', text: '#242424', heading: '#111111', primary: '#1a8917', surface: '#f2f3f5', border: '#eaeaea' }),
  // 46. Stripe 商务
  palette({ id: 'stripe', name: 'Stripe', description: '前沿硅谷极客商务风', bg: '#f6f9fc', text: '#425466', heading: '#0a2540', primary: '#635bff', surface: '#eef0ff' }),
  // 47. Notion 极简
  palette({ id: 'notion', name: 'Notion', description: '极致克制黑白灰，信息密度优先', bg: '#ffffff', text: '#37352f', heading: '#37352f', subheading: '#37352f', primary: '#37352f', surface: '#f7f6f3', border: '#e9e9e7', codeBg: '#f7f6f3', codeText: '#eb5757' }),
  // 48. GitHub 开发者
  palette({ id: 'github', name: 'GitHub', description: '开发者最熟悉的 README 界面', bg: '#ffffff', text: '#1f2328', heading: '#1f2328', subheading: '#1f2328', primary: '#0969da', surface: '#f6f8fa', border: '#d1d9e0', codeBg: '#f6f8fa', codeText: '#1f2328' }),
  // 49. 触摸科技
  palette({ id: 'touch-tech', name: '触摸科技', description: '现代科技触感，玻璃拟态', bg: '#f0f4ff', text: '#1e293b', heading: '#0f172a', primary: '#6366f1', surface: '#e0e7ff', border: '#c7d2fe' }),
  // 50. 深空黑
  palette({ id: 'space-black', name: '深空黑', description: '极简深空，宇宙感', bg: '#0a0a0f', text: '#e0e0e8', heading: '#ffffff', primary: '#a78bfa', surface: '#1a1a25', surfaceText: '#cccccc', border: '#2a2a35', codeBg: '#1a1a2e', codeText: '#a78bfa', isDark: true }),
];

export const md2wechatThemes: Theme[] = PALETTES.map((p) => ({
  id: p.id,
  name: p.name,
  description: p.description,
  styles: makeStyles(p),
}));